name: Scheduled Gmail Sync

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Scheduled Sync
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.APP_URL }}/api/sync/scheduled"
        env:
          APP_URL: ${{ secrets.APP_URL }}

# To use this:
# 1. Go to your GitHub repo > Settings > Secrets and variables > Actions
# 2. Add these secrets:
#    - CRON_SECRET: your-secret-cron-key-change-this-in-production
#    - APP_URL: https://your-app.vercel.app